### PR TITLE
Add ability to set HTTP headers per feed

### PR DESCRIPTION
**Pull request by urbantrout**

### CODE REVIEW

**Comment by engram-design** [comment]
Thanks for this, however I would like to shelve this for the moment as we'll be adding more full-featured authentication and handling. Thanks!

**Comment by urbantrout** [comment]
Looking forward to your solution.

**Comment by stigzelm** [comment]
Yes, I would also like to know your solution for putting different http headers per feed.

**Comment by urbantrout** [comment]
I created a separate branch to keep things simple: https://github.com/urbantrout/feed-me/tree/http-headers

**Pull request closed without merging**
